[package]
name = "rust-iot-playground"
version = "0.1.0"
authors = ["Jupp Mueller <jupp0r@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
